### ISSUE TITLE
Consider hosting documentation online

### ISSUE THREAD

**Issue by nilsdeppe** [wokast/RePrimAnd#1]
Nice library! Maybe I missed this in the readme, but it would be great if the documentation were hosted online using something like gh-pages or ReadTheDocs. While not terribly difficult, it felt a tad tedious to have to clone the code, install dependencies, and build the documentation to be able to view the documentation. Probably GitHub Actions+ReadTheDocs would provide a nice solution :)

**Comment by wokast** [comment]
Indeed, hosting the full documentation online is planned but simply not done yet.

**Comment by wokast** [comment]
Documentation is now available online and linked in the project README.
