### ISSUE TITLE
units for E and B fields not documented

### ISSUE THREAD

**Issue by rhaas80** [wokast/RePrimAnd#11]
Reading the documentation (docsrc/sphinx/notation.html) there is no unit given for electric or magnetic fields nor is it defined if factors of $\sqrt{4\pi}$ have been included or not (which is sometimes done). See eg https://www.einsteintoolkit.org/thornguide/EinsteinBase/HydroBase/documentation.html#x1-30003

**Comment by rhaas80** [comment]
docsrc/sphinx/eos_thermal_files.html does not define what the pseudo-entropy `gm1` (g-1) is that is used for `save_thermal_hybrid_table`

**Comment by wokast** [comment]
Units for E and B are indeed missing in the documentation, but E and B are defined in the corresponding paper about the C2P. Will update sphinx documentation in next commit.

pseudo-enthalpy is defined in the sphinx documentation under Barotropic EOS / Features. Will add a link in eos_thermal_files.html  to make it easier to find.

**Comment by wokast** [comment]
Added definition of E and B used in code+paper but do not explain the unholy mess that is electromagnetic unit systems.. 
Added links for pseudo-enthalpy where needed.
