### ISSUE TITLE
document and require miminum GSL version

### ISSUE THREAD

**Issue by rhaas80** [wokast/RePrimAnd#19]
RePrimAnd uses gsl_interp_steffen which is GSL 2 only. 

The minimum version required (2.0) should be documented, and ideally tested for (though meson may already do so, just the simplistic Makefile does not).

Currently this means that RePrimAnd cannot be used with the GSL tarball in the ET (which is 1.16).

After the next release the included tarball can be updated and a VERSION tag added to GSL which the ExternalLibraries thorn could check for.

**Comment by wokast** [comment]
GSL 1.16 is severely outdated. However, the documentation should indeed state the minimum version required. This will become moot in the near future: the plan is to replace GSL altogether in favor of boost.

**Comment by wokast** [comment]
v1.4 includes check for minimum version
