### ISSUE TITLE
confusing license information in Reprimand thorn

### ISSUE THREAD

**Issue by rhaas80** [wokast/RePrimAnd#4]
The readme file of the reprimand thorn states:

Licence      : GPL

which is however only the license of the thorn files and not the license of the included source code archive, which is CC-SA-NC v4 and not compatible with GPL. My guess would be that the git repository is a "derived product" in the sense of GPL (just like a tarball would be) so GPLv2 would want to encompass the source code tarball. Simplest fix is probably to make that thorn license match the tarball license. GPLv3 may also work since it makes a distinction between "aggregate" and modified distribution and one could (possibly) consider that git repository an aggregate. Moslty and issue for anyone who would like to re-distribute the code and not for this repository itself.

**Comment by wokast** [comment]
Thanks for reporting. The different licenses are not deliberate, I simply forgot to edit the Readme file License entry. Everything in this repo should have the same license (creative commons for now). Will synchronize the thorn Readme file in next bugfix release.

**Comment by rhaas80** [comment]
thank you. that will certainly avoid confusion.

**Comment by wokast** [comment]
Fixed in commit 1582722ca872643db2fe0413331f78c6396929f9, closing.
