### ISSUE TITLE
document way to override location of HDF5 and BOOST library away from PKG_CONFIG

### ISSUE THREAD

**Issue by rhaas80** [wokast/RePrimAnd#9]
There should be a way to override the dependency packages directories. Meson seems to have such a way: https://github.com/mesonbuild/meson/issues/5616 but I have not yet tried this with RePrimAnd. 

This is useful in case pkg-config is not available (eg HDF5 will not build pkg-config all the time). https://github.com/Homebrew/homebrew-core/issues/61490 and https://github.com/HDFGroup/hdf5/blob/e54f5a14d28cf9eb1226ce7feab2e2600d3984b4/release_docs/HISTORY-1_10.txt#L370-L375

**Comment by wokast** [comment]
Not sure how to fix this. BOOST and HDF5 packaging is a mess in general. Probably the documentation should at least mention the need to properly install those dependencies.

**Comment by rhaas80** [comment]
Oh, in my case HDF5 *was* "properly" installed :-). Namely came out of homebrew which was the sole package manager installed on that particular mac.  Just turns out that Homebrew builds is HDF5 without using cmake so there is no pkg-config file created and thus they do not ship one.

**Comment by wokast** [comment]
The readme explains the need for pkgconf files for hdf5 ("Make sure there is a pkg-config file for the version you want to build with."). It also has some hints about boost. Conversely, meson does not seem to have a good way to deal with botched boost and hdf5 installations. setting to wontfix for now.
